version: '3.9'
services:
  db:
    image: postgres:16
    container_name: docservice_postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
